In [1]:
#load libraries
import pandas as pd
from sklearn import datasets

In [2]:
data = datasets.load_iris()

In [3]:
data.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
#make DataFrame
iris_df = pd.DataFrame(data.data,columns=[data.feature_names])

In [7]:
iris_df.head()

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm)
0               5.1              3.5               1.4              0.2
1               4.9              3.0               1.4              0.2
2               4.7              3.2               1.3              0.2
3               4.6              3.1               1.5              0.2
4               5.0              3.6               1.4              0.2

In [8]:
iris_df2 = pd.concat((iris_df,pd.DataFrame(data.target)),axis=1)

In [9]:
iris_df2.head()

(sepal length (cm),)  (sepal width (cm),)  (petal length (cm),)  \
0                   5.1                  3.5                   1.4   
1                   4.9                  3.0                   1.4   
2                   4.7                  3.2                   1.3   
3                   4.6                  3.1                   1.5   
4                   5.0                  3.6                   1.4   

   (petal width (cm),)  0  
0                  0.2  0  
1                  0.2  0  
2                  0.2  0  
3                  0.2  0  
4                  0.2  0

In [13]:
iris_df2 = iris_df2.rename(columns={0:'Species'})

In [14]:
iris_df2.head()

(sepal length (cm),)  (sepal width (cm),)  (petal length (cm),)  \
Species                   5.1                  3.5                   1.4   
1                         4.9                  3.0                   1.4   
2                         4.7                  3.2                   1.3   
3                         4.6                  3.1                   1.5   
4                         5.0                  3.6                   1.4   

         (petal width (cm),)  Species  
Species                  0.2        0  
1                        0.2        0  
2                        0.2        0  
3                        0.2        0  
4                        0.2        0

In [17]:
iris_df2 = iris_df2.rename(columns=({'(sepal length (cm),)':'sepal length','(sepal width (cm),)':'sepal width','(petal length (cm),)':'petal width','(petal width (cm),)':'petal   width'}))

In [18]:
iris_df2.head()

(sepal length (cm),)  (sepal width (cm),)  (petal length (cm),)  \
Species                   5.1                  3.5                   1.4   
1                         4.9                  3.0                   1.4   
2                         4.7                  3.2                   1.3   
3                         4.6                  3.1                   1.5   
4                         5.0                  3.6                   1.4   

         (petal width (cm),)  Species  
Species                  0.2        0  
1                        0.2        0  
2                        0.2        0  
3                        0.2        0  
4                        0.2        0

In [19]:
x = data.data
y = data.target

In [20]:
#split data into train and test
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=40)

In [22]:
#build model
from sklearn.tree import DecisionTreeClassifier

In [23]:
#using entropy
dc_entropy = DecisionTreeClassifier(criterion = 'entropy',max_depth=3)
dc_entropy.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3)

In [24]:
dc_entropy.get_n_leaves()

5

In [27]:
#predict
preds = dc_entropy.predict(x_test)

In [26]:
y_test

array([0, 1, 2, 2, 1, 2, 1, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 1, 2, 2,
       1, 0, 1, 0, 0, 2, 0, 1])

In [28]:
pd.crosstab(y_test,preds)

col_0  0   1  2
row_0          
0      8   0  0
1      0  12  0
2      0   1  9

In [29]:
#accuracy
import numpy as np
np.mean(preds==y_test)

0.9666666666666667

In [30]:
#classification report
from sklearn.metrics import classification_report
classification_report(preds,y_test)

'              precision    recall  f1-score   support\n\n           0       1.00      1.00      1.00         8\n           1       1.00      0.92      0.96        13\n           2       0.90      1.00      0.95         9\n\n    accuracy                           0.97        30\n   macro avg       0.97      0.97      0.97        30\nweighted avg       0.97      0.97      0.97        30\n'

## using gini **criteria**

In [31]:
dc_gini = DecisionTreeClassifier(criterion='gini', max_depth=3)
dc_gini.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=3)

In [32]:
preds2 = dc_gini.predict(x_test)
preds2

array([0, 1, 2, 2, 1, 2, 1, 1, 1, 0, 1, 0, 0, 1, 1, 2, 2, 2, 1, 1, 2, 2,
       1, 0, 1, 0, 0, 2, 0, 1])

In [33]:
y_test

array([0, 1, 2, 2, 1, 2, 1, 1, 1, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1, 1, 2, 2,
       1, 0, 1, 0, 0, 2, 0, 1])

# Accuracy

In [34]:
np.mean(preds2==y_test)

0.9666666666666667

# Decision Tree Regression

In [35]:
from sklearn.tree import DecisionTreeRegressor

In [36]:
iris_df2.head()

(sepal length (cm),)  (sepal width (cm),)  (petal length (cm),)  \
Species                   5.1                  3.5                   1.4   
1                         4.9                  3.0                   1.4   
2                         4.7                  3.2                   1.3   
3                         4.6                  3.1                   1.5   
4                         5.0                  3.6                   1.4   

         (petal width (cm),)  Species  
Species                  0.2        0  
1                        0.2        0  
2                        0.2        0  
3                        0.2        0  
4                        0.2        0

In [37]:
x = iris_df2.iloc[:,0:3]
y = iris_df2.iloc[:,3]

In [38]:
dc_regression = DecisionTreeRegressor()

In [39]:
X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.2,random_state=30)

In [40]:
dc_regression.fit(X_train,Y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


DecisionTreeRegressor()

In [41]:
dc_regression.score(X_test,Y_test)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:1692: FutureWarning: Feature names only support names that are all strings. Got feature names with dtypes: ['tuple']. An error will be raised in 1.2.
  FutureWarning,


0.9600066655557408